# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimentservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xperimentservice.proto\x12\x04grpc\"\x07\n\x05\x45mpty\")\n\x05State\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\t\"D\n\x08GameSync\x12\x0e\n\x06screen\x18\x01 \x01(\x0c\x12\x12\n\ntime_limit\x18\x02 \x01(\t\x12\x14\n\x0c\x65lapsed_time\x18\x03 \x01(\t2\x99\x01\n\x11\x45xperimentService\x12*\n\x0cServerSignal\x12\x0b.grpc.Empty\x1a\x0b.grpc.State0\x01\x12/\n\x0eGameSyncSignal\x12\x0e.grpc.GameSync\x1a\x0b.grpc.Empty(\x01\x12\'\n\x0bHealthCheck\x12\x0b.grpc.Empty\x1a\x0b.grpc.Emptyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_STATE = DESCRIPTOR.message_types_by_name['State']
_GAMESYNC = DESCRIPTOR.message_types_by_name['GameSync']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'experimentservice_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'experimentservice_pb2'
  # @@protoc_insertion_point(class_scope:grpc.State)
  })
_sym_db.RegisterMessage(State)

GameSync = _reflection.GeneratedProtocolMessageType('GameSync', (_message.Message,), {
  'DESCRIPTOR' : _GAMESYNC,
  '__module__' : 'experimentservice_pb2'
  # @@protoc_insertion_point(class_scope:grpc.GameSync)
  })
_sym_db.RegisterMessage(GameSync)

_EXPERIMENTSERVICE = DESCRIPTOR.services_by_name['ExperimentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=33
  _EMPTY._serialized_end=40
  _STATE._serialized_start=42
  _STATE._serialized_end=83
  _GAMESYNC._serialized_start=85
  _GAMESYNC._serialized_end=153
  _EXPERIMENTSERVICE._serialized_start=156
  _EXPERIMENTSERVICE._serialized_end=309
# @@protoc_insertion_point(module_scope)
