# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import experimentservice_pb2 as experimentservice__pb2


class ExperimentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerSignal = channel.unary_stream(
                '/grpc.ExperimentService/ServerSignal',
                request_serializer=experimentservice__pb2.Empty.SerializeToString,
                response_deserializer=experimentservice__pb2.State.FromString,
                )
        self.GameSyncSignal = channel.stream_unary(
                '/grpc.ExperimentService/GameSyncSignal',
                request_serializer=experimentservice__pb2.GameSync.SerializeToString,
                response_deserializer=experimentservice__pb2.Empty.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/grpc.ExperimentService/HealthCheck',
                request_serializer=experimentservice__pb2.Empty.SerializeToString,
                response_deserializer=experimentservice__pb2.Empty.FromString,
                )


class ExperimentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ServerSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GameSyncSignal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExperimentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerSignal': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerSignal,
                    request_deserializer=experimentservice__pb2.Empty.FromString,
                    response_serializer=experimentservice__pb2.State.SerializeToString,
            ),
            'GameSyncSignal': grpc.stream_unary_rpc_method_handler(
                    servicer.GameSyncSignal,
                    request_deserializer=experimentservice__pb2.GameSync.FromString,
                    response_serializer=experimentservice__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=experimentservice__pb2.Empty.FromString,
                    response_serializer=experimentservice__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ExperimentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExperimentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ServerSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ExperimentService/ServerSignal',
            experimentservice__pb2.Empty.SerializeToString,
            experimentservice__pb2.State.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GameSyncSignal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grpc.ExperimentService/GameSyncSignal',
            experimentservice__pb2.GameSync.SerializeToString,
            experimentservice__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ExperimentService/HealthCheck',
            experimentservice__pb2.Empty.SerializeToString,
            experimentservice__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
